### ISSUE TITLE
[DONE] MotorPH employee application with record  create functionality

### ISSUE THREAD

**Issue by J0eychnpulpey** [eliakimset/MO-IT103-A1101-CP2-Group-4#10]
- [x] The Development Team has set a meeting to review the codes of everyone in the team following the implementation of the changes filed under the change request document MPHCR-02. You will discuss with your team the codes that you came up with.

During the meeting, each member of the team will:

Present your output for Laboratory Work #4. Provide a walkthrough of the input-process-output sequence of your program;
Discuss the code with your teammates; and
Your team will sync up based on the best practices each member of your team has done in their output and codes. Discuss why they need to be integrated into your group output.
Finalize your group’s output.

**Comment by J0eychnpulpey** [comment]
- [x] HOMEWORK #4: MotorPH employee application with record create functionality

**Comment by eliakimset** [comment]
try to use netbeans instead

**Comment by J0eychnpulpey** [comment]
@eliakimset It works now. tnx

![image](https://github.com/eliakimset/MO-IT103-A1101-CP2-Group-4/assets/106713068/4714677a-b413-464d-928a-da3bed9aa7a3)
