### ISSUE TITLE
In my end, using Vscode IDE I can't scroll down the remaining buttom of the applicaton.

### ISSUE THREAD

**Issue by J0eychnpulpey** [eliakimset/MO-IT103-A1101-CP2-Group-4#4]
![image](https://github.com/eliakimset/MO-IT103-A1101-CP2-Group-4/assets/106713068/2615723b-9c3c-471b-b037-a7323ec65935)

**Comment by eliakimset** [comment]
will adjust the sizing

**Comment by J0eychnpulpey** [comment]
sige po

**Comment by J0eychnpulpey** [comment]
Fixing issues related to missing imports for layout management classes in Java Swing, such as BorderLayout, JScrollPane, and JPanel.
